### ISSUE TITLE
 yarn build error

### ISSUE THREAD

**Issue by wushi777** [netless-io/netless-rtc-react-whiteboard#54]
> yarn build
yarn run v1.15.2
$ rimraf build && NODE_ENV=production react-app-rewired --max-old-space-size=4096 build --scripts-version react-scripts-ts
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed with exit code 1.

**Comment by buhe** [comment]
感谢反馈，
你应该是用了 windows 构建，我们优化一下，采用 CROSS_ENV 修复

**Comment by buhe** [comment]
修复前可以去掉 NODE_ENV=production
